language: node_js

node_js:
  - 6
  - 7

matrix:
  fast_finish: true

env:
  - CXX=g++-4.8

cache:
  yarn: true
  # directories:
  #  - node_modules

# Via: https://yarnpkg.com/en/docs/install-ci#travis-tab
before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  slack:
    secure: M/y2fypVRp87ldDszJvXXCWMuCyNF/OiWtp4OVZaPbgd8fbsXX2nSyvNARLf+wWccboVVPlaPaF8tDM/HBnR74rJbT6vl5igFL5EvARJ5AttagH1TODabPv0LtBYVPy8wZhfbT7XesghCOD8jGbsuO+r/6hUV9XxHLnEW5NckfuGJSD2vr9A+WDf1NaY18fz5C/XsdOF6Vh6TF2Vq8D4KsoOENMAvwfcTMyikp4BjNUQWCe301U4yaAn0u5SmdN2eP9eTHxUTBNpG3GkSk994Q/0iZedYQAn38rnIybkj6BsMVFxBHkzUtbsKH2U/qxxZqx5IM9FWz/7rb55NYuNY7ZbXNQ3n391hAuiXM1AIGYHBxCtAcQdNUAO0ogVYueG2ajqQVlJSMnBo/VQE1/dVIJ9Gn8KjjJY5jr1u7jG86SIWeVSEEntsNfvdavBO9D8YSEV72KHZdjtJoidZQkUY7S3Wpp++OFR4h5ZLDHgDiQFEEZPPpzwdsHOicRZnYXe0YYuaWeUxg3zVJvgfuPAJHXDclJZoKWFazblPF8tXSijEiek/JIR1ZimnXlKkoCpXQGfjzZPYAMq3KXx5cLhk8QuzCzuAdD5e9pmpY0ml3D8eQ5gjQ3imh5FS4SdMi/AxiHau22ErB12V81hxzb9ZOtjSZTBPIDdWCOGkbpa4yw=
